add cleanup job & fix build

diff --git a/.github/workflows/create-percy-snapshots.yml b/.github/workflows/create-percy-snapshots.yml
--- a/.github/workflows/create-percy-snapshots.yml
+++ b/.github/workflows/create-percy-snapshots.yml
@@ -13,6 +13,7 @@ jobs:
     runs-on: ubuntu-latest
     outputs:
       pr_head_sha: ${{ steps.get_pr_data.outputs.sha }}
+      pr_number: ${{ steps.get_pr_data.outputs.pr }}
       percy_build_link: ${{ steps.percy_snapshot.outputs.build_link }}
       percy_org_id: ${{ steps.percy_snapshot.outputs.org_id }}
       percy_build_id: ${{ steps.percy_snapshot.outputs.build_id }}
@@ -24,6 +25,9 @@ jobs:
       - name: Checkout SCM
         uses: actions/checkout@v4
 
+      - name: Remove SCM files that will be replaced by artifact files
+        run: rm -rf scss/ templates/docs/examples/
+
       - name: Download artifact from workflow run
         uses: actions/download-artifact@v4
         with:
@@ -31,6 +35,12 @@ jobs:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           repository: ${{ github.event.workflow_run.repository.full_name }}
           run-id: ${{ github.event.workflow_run.id }}
+
+      - name: Move artifact files into place to replace SCM
+        run: |
+          set -e
+          mv examples/ templates/docs/.
+          tree
 
       - name: Get PR data
         if: github.event.workflow_run.event=='pull_request'
@@ -68,13 +78,6 @@ jobs:
           else
             echo "Previous workflow run was successful."
           fi
-
-      - name: Replace SCM files with artifact files
-        run: |
-          set -e
-          rm -rf templates/docs/examples/ scss/
-          mv examples/ templates/docs/.
-          tree
 
       - name: Install NodeJS
         uses: actions/setup-node@v4.0.2
@@ -173,7 +176,7 @@ jobs:
         id: create_percy_final_status_check
         uses: octokit/request-action@v2.x
         with:
-          route: POST /repos/${{github.repository}}/check-runs
+          route: POST /repos/${{ github.repository }}/check-runs
           owner: octokit
           repo: request-action
           name: "percy_upload"
@@ -189,5 +192,32 @@ jobs:
               Build is associated with PR https://github.com/${{github.repository}}/pull/${{ steps.get_pr_data.outputs.pr }}
               There were ${{ steps.percy_build_results.outputs.num_snapshots }} total snapshot(s) taken.
               The review state reason is: ${{ steps.percy_build_results.outputs.review_state_reason }}
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  failure_cleanup:
+    runs-on: ubuntu-latest
+    needs: upload
+    if: ${{ failure() }}
+    steps:
+      - name: Set Percy status check to failed
+        if: ${{ github.event.workflow_run.event=='pull_request' }}
+        uses: octokit/request-action@v2.x
+        with:
+          route: POST /repos/${{ github.repository }}/check-runs
+          owner: octokit
+          repo: request-action
+          name: "percy_upload"
+          head_sha: ${{ needs.upload.outputs.percy_build_link  }}
+          status: completed
+          conclusion: failure
+          details_url: ${{ needs.upload.outputs.pr_head_sha }}
+          output: |
+            title: "Percy build"
+            summary: "Percy build #${{ needs.upload.outputs.percy_build_id }} failed: ${{ needs.upload.outputs.percy_review_state || 'Unknown review state' }}"
+            text: |
+              Percy build failed or did not start.
+              Build is associated with PR https://github.com/${{ github.repository }}/pull/${{ needs.upload.outputs.pr_number }}
+              There were ${{ needs.upload.outputs.percy_num_snapshots }} total snapshot(s) taken.
+              The review state reason is: ${{ needs.upload.outputs.percy_review_state_reason }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
